name: Notification on push

on:
  release:
    types: [published]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Teste 01
        DISCORD_AVATAR: https://raw.githubusercontent.com/LeGitHubDeTai/github-to-discord/main/icon.png
        MESSAGE_TITLE: New Version
        MESSAGE_DESCRIPTION: Github Action By Tai Studio
        MESSAGE_URL: https://github.com/LeGitHubDeTai/AnimeBack
        MESSAGE_COLOR: 5814783
        CONTENT: null
        MESSAGE_TITLE: "New Version"
        MESSAGE_DESCRIPTION: "Teste 02"
        MESSAGE_URL: 'https://github.com/LeGitHubDeTai/github-to-discord'
        SECTION_NAME: "ChangeLog"
        AUTHOR_NAME: "Teste 03"
        AUTHOR_URL: "Teste 04"
        AUTHOR_AVATAR: "Teste 05"
        FOOTER_TEXT: "- Teste 06 -"
        FOOTER_URL: "https://tai-studio.ml/img/icons/Tai_Studio_discord.png"
        IMAGE: null;
